name: rp-28
channels:
  - conda-forge
dependencies:
  - python=3.9
  - einops=0.7.0
  - h5py=3.12.1
  - hdf5=1.14.5
  - ipykernel=6.29.5
  - ipython=8.18.1
  - ipywidgets=8.1.5
  - jupyterlab=4.3.6
  - matplotlib=3.4.2
  - notebook=7.3.3
  - numpy=1.26.4
  - openpyxl=3.1.5
  - oyaml=1.0
  - protobuf=3.20.3
  - pydicom=2.4.4
  - scikit-image=0.19.3
  - scipy=1.13.1
  - tensorboard=2.8.0
  - tqdm=4.67.1
  - xlsxwriter=3.2.2
  - pip
  - pip:
      - tensorflow==2.8.2
      - tensorflow-addons==0.16.1
      - tensorflow-probability==0.16.0
      - cloudpickle==3.1.1